#!/bin/bash

while [ $OPTIND -le $# ]
do
  if getopts 'h' argument
  then
    case $argument in
      h)
        echo "usage: $0 [file ...]"
        echo 'outputs media duration'
        echo ' -h  show this text'
        exit ;;
      \?) exit 1 ;;
    esac
  else
    input+=("${!OPTIND}")
    let OPTIND++
  fi
done

for argument in "${input[@]}"
do
  ffprobe "$argument" 2>&1 | grep -Po '(?<=Duration: )[^,]+(?=,)'
done
