#!/bin/bash

for argument
do
  if [ "$argument" == -h ]
  then
    echo "usage: $0 [file ...]"
    echo 'outputs media duration'
    exit
  fi
done

for argument
do
  ffprobe "$argument" 2>&1 | grep -Po '(?<=Duration: )[^,]+(?=,)'
done
