#!/bin/bash

number='[[:digit:]]{1,2}'
for arg
do
  [[ "$arg" =~ ^(($number):)?(($number):)?($number)(\.($number))?$ ]]
  let "result+= \
    360000 * 10#${BASH_REMATCH[2]:-0} + \
    6000 * 10#${BASH_REMATCH[4]:-0} + \
    100 * 10#${BASH_REMATCH[5]} + \
    10#${BASH_REMATCH[7]:-0}"
done

echo-exist() {
  if [ "$1" -gt 0 ]
  then
    printf "$2%02d$3" "$1"
  fi
}
echo-exist "$(($result / 360000))" '' :
echo-exist "$(($result / 6000 % 60))" '' :
printf "$(($result / 100 % 60))"
echo-exist "$(($result % 100))" .
echo
